dist: xenial
language: python
python: 3.7
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install
# command to run tests
script:
  - pipenv run python -m pytest
deploy:
  on:
    branch: dev
    tags: true
  provider: pypi
  user: $pypi_user
  password: $pypi_password
