dist: xenial
language: python
python: 3.7
# command to install dependencies
before_install:
  - sudo apt-get install jq
  - curl -LSs "$(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url')" -o codacy-coverage-reporter-assembly.jar
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run -m pytest
  - coverage xml
after_success:
  - java -jar codacy-coverage-reporter-assembly.jar report -l Python -r coverage.xml
deploy:
  on:
    branch: dev
    tags: true
  provider: pypi
  user: $pypi_user
  password: $pypi_password
